# Generated by Django 5.0.4 on 2026-04-13 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('roof_type', models.CharField(blank=True, choices=[('flat', 'Flat'), ('pitched', 'Pitched'), ('metal', 'Metal Sheet'), ('tile', 'Tile'), ('concrete', 'Concrete Slab')], max_length=20)),
                ('roof_area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('roof_orientation', models.CharField(blank=True, max_length=50)),
                ('shading_level', models.CharField(choices=[('none', 'No Shading'), ('partial', 'Partial'), ('heavy', 'Heavy')], default='none', max_length=20)),
                ('shading_notes', models.TextField(blank=True)),
                ('grid_status', models.CharField(choices=[('connected', 'Grid Connected'), ('offgrid', 'Off-Grid'), ('unstable', 'Unstable Grid')], default='connected', max_length=20)),
                ('existing_system_notes', models.TextField(blank=True)),
                ('main_breaker_amps', models.IntegerField(blank=True, null=True)),
                ('three_phase', models.BooleanField(default=False)),
                ('db_board_condition', models.CharField(blank=True, max_length=100)),
                ('scaffolding_needed', models.BooleanField(default=False)),
                ('installation_risks', models.TextField(blank=True)),
                ('feasibility', models.CharField(choices=[('feasible', 'Feasible'), ('conditional', 'Conditional'), ('not_feasible', 'Not Feasible')], default='feasible', max_length=20)),
                ('recommended_system_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('surveyor_notes', models.TextField(blank=True)),
                ('photo_roof', models.ImageField(blank=True, null=True, upload_to='surveys/roof/')),
                ('photo_db_board', models.ImageField(blank=True, null=True, upload_to='surveys/db/')),
                ('photo_site', models.ImageField(blank=True, null=True, upload_to='surveys/site/')),
                ('surveyed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='clients.client')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='quotes.quote')),
                ('surveyed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'site_surveys',
                'ordering': ['-created_at'],
            },
        ),
    ]
