# Generated by Django 5.0.4 on 2026-04-13 09:17

import apps.quotes.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(default=apps.quotes.models.generate_ref, max_length=30, unique=True)),
                ('total_daily_kwh', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('design_daily_kwh', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('system_size_kwp', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_load_kw', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('num_panels', models.IntegerField(default=0)),
                ('backup_hours', models.DecimalField(decimal_places=1, default=8, max_digits=5)),
                ('peak_sun_hours', models.DecimalField(decimal_places=1, default=5.5, max_digits=4)),
                ('is_all_in_one_mode', models.BooleanField(default=False)),
                ('panels_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('battery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('inverter_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('generator_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('accessories_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('installation_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price_rwf', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grid_tariff_rwf_kwh', models.DecimalField(decimal_places=2, default=89, max_digits=8)),
                ('annual_savings_rwf', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payback_years', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Client'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('valid_days', models.IntegerField(default=30)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('share_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('battery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='battery_quotes', to='products.product')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to=settings.AUTH_USER_MODEL)),
                ('generator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generator_quotes', to='products.product')),
                ('inverter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inverter_quotes', to='products.product')),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='panel_quotes', to='products.product')),
                ('parent_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='quotes.quote')),
            ],
            options={
                'db_table': 'quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='quotes.quote')),
            ],
            options={
                'db_table': 'client_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('wattage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hours_per_day', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to='quotes.quote')),
            ],
            options={
                'db_table': 'appliances',
            },
        ),
    ]
