# Generated by Django 5.0.4 on 2026-04-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='num_inverters',
            field=models.IntegerField(default=1),
        ),
    ]
