# Generated by Django 5.0.4 on 2026-04-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_add_num_inverters'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='num_batteries',
            field=models.IntegerField(default=1),
        ),
    ]
