# Generated by Django 5.2.7 on 2026-06-20 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0004_quote_type_lineitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('fuel', 'Fuel'), ('materials', 'Materials'), ('salaries', 'Salaries'), ('contractor', 'Contractor Commission'), ('marketing', 'Marketing'), ('transport', 'Transport'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='other', max_length=30)),
                ('amount_rwf', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='quotes.quote')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('fuel', 'Fuel'), ('materials', 'Materials'), ('salaries', 'Salaries'), ('contractor', 'Contractor Commission'), ('marketing', 'Marketing'), ('transport', 'Transport'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='other', max_length=30)),
                ('amount_rwf', models.DecimalField(decimal_places=2, max_digits=14)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('next_due_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recurring_expenses',
                'ordering': ['next_due_date'],
            },
        ),
    ]
