# Generated by Django 5.0.4 on 2026-04-14 07:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='SolarHope Africa', max_length=200)),
                ('company_phone', models.CharField(default='+250 780 348 624', max_length=50)),
                ('company_email', models.EmailField(default='info@solarhopeafrica.com', max_length=254)),
                ('company_website', models.CharField(default='www.solarhopeafrica.com', max_length=200)),
                ('company_tagline', models.CharField(default='Light Up Dreams, The Solar Way', max_length=300)),
                ('grid_tariff_rwf_kwh', models.DecimalField(decimal_places=2, default=Decimal('386'), max_digits=8)),
                ('installation_pct', models.DecimalField(decimal_places=4, default=Decimal('0.10'), max_digits=5)),
                ('accessories_pct', models.DecimalField(decimal_places=4, default=Decimal('0.08'), max_digits=5)),
                ('safety_margin_pct', models.DecimalField(decimal_places=4, default=Decimal('0.20'), max_digits=5)),
                ('default_peak_sun_hours', models.DecimalField(decimal_places=1, default=Decimal('5.5'), max_digits=4)),
                ('default_backup_hours', models.IntegerField(default=8)),
                ('default_valid_days', models.IntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'db_table': 'company_settings',
            },
        ),
    ]
