# Generated by Django 5.0.4 on 2026-04-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='bank_account',
            field=models.CharField(blank=True, default='100229629799', max_length=50),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='bank_name',
            field=models.CharField(blank=True, default='Bank of Kigali', max_length=100),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='company_address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='momo_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='momo_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='payment_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='quote_terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='system_lifespan',
            field=models.CharField(default='25–30 years', max_length=30),
        ),
    ]
