# Generated by Django 5.0.4 on 2026-04-23 12:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='e.g. Standard, Silver, Gold', max_length=100)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for no upper cap', max_digits=14, null=True)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Fraction of deal value (e.g. 0.025 = 2.5%)', max_digits=5)),
            ],
            options={
                'db_table': 'commission_tiers',
                'ordering': ['min_amount'],
            },
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Personal override rate. Leave blank to use global commission tiers.', max_digits=5, null=True),
        ),
    ]
