# Generated by Django 5.2.7 on 2026-06-20 21:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_commissiontier_alter_agentprofile_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='sales_commission_name',
            field=models.CharField(blank=True, default='', help_text='Name of contractor / sales person who earns this commission', max_length=100),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='sales_commission_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.10'), help_text='Fraction of approved quote value paid to contractor (e.g. 0.10 = 10%)', max_digits=5),
        ),
    ]
