# Generated by Django 5.2.7 on 2026-06-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_companysettings_sales_commission_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='company_tin',
            field=models.CharField(blank=True, default='145206514', help_text='TIN number printed on official documents', max_length=50),
        ),
    ]
