# Generated by Django 5.0.4 on 2026-04-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0002_warranty_claims'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationlog',
            name='created_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
