# Generated by Django 5.0.4 on 2026-04-22 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('user_role', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('status_change', 'Status Change'), ('send', 'Send'), ('reset_pin', 'Reset PIN'), ('mark_paid', 'Mark Paid'), ('approve', 'Approve'), ('reject', 'Reject')], max_length=30)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('resource_label', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='activity_lo_user_id_d23b30_idx'), models.Index(fields=['resource_type', 'created_at'], name='activity_lo_resourc_5b55bf_idx'), models.Index(fields=['action', 'created_at'], name='activity_lo_action_0f3584_idx'), models.Index(fields=['created_at'], name='activity_lo_created_166e11_idx')],
            },
        ),
    ]
