# Generated by Django 5.0.4 on 2026-04-13 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('client_type', models.CharField(choices=[('residential', 'Residential'), ('school', 'School / Institution'), ('clinic', 'Clinic / Health Facility'), ('business', 'Business / Hotel'), ('community', 'Community / Mini-grid')], default='residential', max_length=20)),
                ('is_offgrid', models.BooleanField(default=False, help_text='True if no grid connection')),
                ('monthly_bill_rwf', models.DecimalField(blank=True, decimal_places=2, help_text='Last monthly electricity bill in RWF', max_digits=12, null=True)),
                ('monthly_kwh', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly kWh consumption', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('quoted', 'Quoted'), ('followup', 'Follow Up'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('source', models.CharField(blank=True, help_text='How did client hear about us (referral, social media, etc.)', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
