# Generated by Django 5.0.4 on 2026-04-22 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='source_agent',
            field=models.ForeignKey(blank=True, help_text='Field agent who found this client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
