# Generated by Django 5.0.4 on 2026-04-13 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('panel', 'Solar Panel'), ('battery', 'Battery'), ('inverter', 'Inverter'), ('generator', 'All-in-One Generator'), ('accessory', 'Accessory / BOS')], max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price_rwf', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wattage_wp', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('panel_efficiency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('panel_dimensions', models.CharField(blank=True, max_length=50)),
                ('capacity_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('voltage_v', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('battery_cycles', models.IntegerField(blank=True, null=True)),
                ('power_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('inverter_type', models.CharField(blank=True, max_length=50)),
                ('phase', models.CharField(blank=True, choices=[('single', 'Single Phase'), ('three', 'Three Phase')], max_length=10)),
                ('is_all_in_one', models.BooleanField(default=False, help_text='Battery + inverter combined unit')),
                ('max_pv_input_w', models.IntegerField(blank=True, help_text='Max total PV input in Watts', null=True)),
                ('min_panel_wp', models.DecimalField(blank=True, decimal_places=2, help_text='Min panel size (Wp)', max_digits=8, null=True)),
                ('max_panel_wp', models.DecimalField(blank=True, decimal_places=2, help_text='Max panel size per unit (Wp)', max_digits=8, null=True)),
                ('builtin_inverter_kw', models.DecimalField(blank=True, decimal_places=2, help_text='Built-in inverter power (kW)', max_digits=8, null=True)),
                ('builtin_capacity_kwh', models.DecimalField(blank=True, decimal_places=2, help_text='Built-in battery capacity (kWh)', max_digits=8, null=True)),
                ('warranty_years', models.IntegerField(default=5)),
                ('linear_warranty_years', models.IntegerField(blank=True, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['category', 'name'],
            },
        ),
    ]
